using System;
using System.Collections.Generic;

namespace MLBDraft.API.Entities
{
    public static class MLBDraftContextExtensions
    {
        public static void EnsureSeedDataForContext(this MLBDraftContext context){

            context.Players.RemoveRange(context.Players);
            context.SaveChanges();

            var players = new List<Player>()
            {
                new Player()
                {
                    Id = new Guid("7d9bafc1-2274-407a-a7cd-60e2f6ba496e"),
                    FirstName = "J.T.",
                    LastName = "Realmuto",
                    ImagePath = "",
                    Team = "PHI",
                    Position = "C",
                    BattingAverage = ".277",
                    HomeRuns = "21",
                    Runs = "74",
                    RunsBattedIn = "74",
                    StolenBases = "3",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("693b55c4-60ea-4b06-b512-e6dd4a2a0bbb"),
                    FirstName = "Salvador",
                    LastName = "Perez",
                    ImagePath = "",
                    Team = "KC",
                    Position = "C",
                    BattingAverage = ".235",
                    HomeRuns = "27",
                    Runs = "52",
                    RunsBattedIn = "80",
                    StolenBases = "1",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("448e7ae2-cf85-4058-aa7a-3fe5cbd9ee75"),
                    FirstName = "Wilson",
                    LastName = "Contreras",
                    ImagePath = "",
                    Team = "CHC",
                    Position = "C",
                    BattingAverage = ".249",
                    HomeRuns = "54",
                    Runs = "50",
                    RunsBattedIn = "54",
                    StolenBases = "4",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("f2d2aefe-ff6e-4d40-9656-c5dd01a735ab"),
                    FirstName = "Buster",
                    LastName = "Posey",
                    ImagePath = "",
                    Team = "SF",
                    Position = "C",
                    BattingAverage = ".284",
                    HomeRuns = "5",
                    Runs = "47",
                    RunsBattedIn = "41",
                    StolenBases = "3",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("ecaf9cd8-0fb7-4804-8029-8b717d0bb493"),
                    FirstName = "Yadier",
                    LastName = "Molina",
                    ImagePath = "",
                    Team = "STL",
                    Position = "C",
                    BattingAverage = ".261",
                    HomeRuns = "20",
                    Runs = "55",
                    RunsBattedIn = "74",
                    StolenBases = "4",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("d5553712-08d3-416d-8477-9d04afccfb08"),
                    FirstName = "Freddie",
                    LastName = "Freeman",
                    ImagePath = "",
                    Team = "ATL",
                    Position = "1B",
                    BattingAverage = ".309",
                    HomeRuns = "23",
                    Runs = "94",
                    RunsBattedIn = "98",
                    StolenBases = "10",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("20675dfb-89c1-4d0e-a3c0-6eccdffb23e0"),
                    FirstName = "Paul",
                    LastName = "Goldschmidt",
                    ImagePath = "",
                    Team = "STL",
                    Position = "1B",
                    BattingAverage = ".290",
                    HomeRuns = "33",
                    Runs = "95",
                    RunsBattedIn = "83",
                    StolenBases = "7",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("25081e0d-350e-4c60-a09f-df9687199151"),
                    FirstName = "Anthony",
                    LastName = "Rizzo",
                    ImagePath = "",
                    Team = "CHC",
                    Position = "1B",
                    BattingAverage = ".283",
                    HomeRuns = "25",
                    Runs = "74",
                    RunsBattedIn = "101",
                    StolenBases = "6",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("f200b117-41fc-416f-acd3-c5cdc7cf3cb0"),
                    FirstName = "Joey",
                    LastName = "Votto",
                    ImagePath = "",
                    Team = "CIN",
                    Position = "1B",
                    BattingAverage = ".284",
                    HomeRuns = "12",
                    Runs = "67",
                    RunsBattedIn = "67",
                    StolenBases = "2",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("5e109be4-45d6-4b09-9d64-ab2cef47e0de"),
                    FirstName = "Albert",
                    LastName = "Pujols",
                    ImagePath = "",
                    Team = "LAA",
                    Position = "1B",
                    BattingAverage = ".245",
                    HomeRuns = "19",
                    Runs = "50",
                    RunsBattedIn = "64",
                    StolenBases = "1",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("71e64d75-1097-41a3-a887-0e2b12c5c6e6"),
                    FirstName = "Jose",
                    LastName = "Altuve",
                    ImagePath = "",
                    Team = "HOU",
                    Position = "2B",
                    BattingAverage = ".316",
                    HomeRuns = "13",
                    Runs = "84",
                    RunsBattedIn = "61",
                    StolenBases = "17",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("a3640c6c-0e1d-4e47-814e-62f89c2c0d8a"),
                    FirstName = "Ozzie",
                    LastName = "Albies",
                    ImagePath = "",
                    Team = "ATL",
                    Position = "2B",
                    BattingAverage = ".261",
                    HomeRuns = "24",
                    Runs = "105",
                    RunsBattedIn = "72",
                    StolenBases = "14",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("2f98ae62-34c0-4dcc-b1c3-4cf41bc64ebf"),
                    FirstName = "Whit",
                    LastName = "Merrifield",
                    ImagePath = "",
                    Team = "KC",
                    Position = "2B",
                    BattingAverage = ".304",
                    HomeRuns = "12",
                    Runs = "88",
                    RunsBattedIn = "60",
                    StolenBases = "45",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("ae72100e-7f50-4c5d-bee4-2d6db4ad0ad5"),
                    FirstName = "DJ",
                    LastName = "LeMahieu",
                    ImagePath = "",
                    Team = "NYY",
                    Position = "2B",
                    BattingAverage = ".276",
                    HomeRuns = "15",
                    Runs = "90",
                    RunsBattedIn = "62",
                    StolenBases = "6",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("7ff5d447-3f5f-44c7-b2ee-07fd6454b6c7"),
                    FirstName = "Starlin",
                    LastName = "Castro",
                    ImagePath = "",
                    Team = "MIA",
                    Position = "2B",
                    BattingAverage = ".278",
                    HomeRuns = "12",
                    Runs = "76",
                    RunsBattedIn = "54",
                    StolenBases = "6",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("fb1787a0-f08b-4a4a-bf51-918cacc4c8c8"),
                    FirstName = "Trea",
                    LastName = "Turner",
                    ImagePath = "",
                    Team = "WAS",
                    Position = "SS",
                    BattingAverage = ".271",
                    HomeRuns = "19",
                    Runs = "103",
                    RunsBattedIn = "73",
                    StolenBases = "43",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("5742c08a-e076-4e9e-93be-1361b60d02f0"),
                    FirstName = "Francisco",
                    LastName = "Lindor",
                    ImagePath = "",
                    Team = "CLE",
                    Position = "SS",
                    BattingAverage = ".277",
                    HomeRuns = "38",
                    Runs = "129",
                    RunsBattedIn = "92",
                    StolenBases = "25",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("6079e089-3405-4454-b666-7e3d6f0abfd6"),
                    FirstName = "Alex",
                    LastName = "Bregman",
                    ImagePath = "",
                    Team = "HOU",
                    Position = "SS",
                    BattingAverage = ".286",
                    HomeRuns = "31",
                    Runs = "105",
                    RunsBattedIn = "103",
                    StolenBases = "10",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("59d90331-693c-468b-961e-75e5b1cd2a94"),
                    FirstName = "Didi",
                    LastName = "Gregorius",
                    ImagePath = "",
                    Team = "NYY",
                    Position = "SS",
                    BattingAverage = ".268",
                    HomeRuns = "27",
                    Runs = "89",
                    RunsBattedIn = "86",
                    StolenBases = "10",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("4af0341c-a285-4f79-931d-3bb653a177e2"),
                    FirstName = "Xander",
                    LastName = "Bogaerts",
                    ImagePath = "",
                    Team = "BOS",
                    Position = "SS",
                    BattingAverage = ".288",
                    HomeRuns = "23",
                    Runs = "72",
                    RunsBattedIn = "103",
                    StolenBases = "8",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("7982dda0-6d06-48b6-8d98-475d01693ed6"),
                    FirstName = "Nolan",
                    LastName = "Arenado",
                    ImagePath = "",
                    Team = "COL",
                    Position = "3B",
                    BattingAverage = ".297",
                    HomeRuns = "38",
                    Runs = "104",
                    RunsBattedIn = "110",
                    StolenBases = "2",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("1457f9b7-ee19-412f-bc75-70a0592edd93"),
                    FirstName = "Jose",
                    LastName = "Ramirez",
                    ImagePath = "",
                    Team = "CLE",
                    Position = "3B",
                    BattingAverage = ".270",
                    HomeRuns = "38",
                    Runs = "110",
                    RunsBattedIn = "105",
                    StolenBases = "34",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("f72cf4ea-cde1-4d3f-9c2d-c37750002e2f"),
                    FirstName = "Miguel",
                    LastName = "Andujar",
                    ImagePath = "",
                    Team = "NYY",
                    Position = "3B",
                    BattingAverage = ".297",
                    HomeRuns = "27",
                    Runs = "92",
                    RunsBattedIn = "83",
                    StolenBases = "2",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("9f5efc60-0cf4-4436-82d2-f262842521f4"),
                    FirstName = "Evan",
                    LastName = "Longoria",
                    ImagePath = "",
                    Team = "SF",
                    Position = "3B",
                    BattingAverage = ".244",
                    HomeRuns = "16",
                    Runs = "51",
                    RunsBattedIn = "54",
                    StolenBases = "3",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("85ad97a5-8de9-4203-9c5f-3b4e02d9bf4d"),
                    FirstName = "Anthony",
                    LastName = "Rendon",
                    ImagePath = "",
                    Team = "WAS",
                    Position = "3B",
                    BattingAverage = ".308",
                    HomeRuns = "24",
                    Runs = "88",
                    RunsBattedIn = "92",
                    StolenBases = "2",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("0afd77bb-9b31-4434-bef4-bb3c23592b6d"),
                    FirstName = "Nicholas",
                    LastName = "Castellanos",
                    ImagePath = "",
                    Team = "DET",
                    Position = "OF",
                    BattingAverage = ".298",
                    HomeRuns = "23",
                    Runs = "88",
                    RunsBattedIn = "89",
                    StolenBases = "2",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("4adcf3cd-366e-47ee-ab6b-eb3368d78bf8"),
                    FirstName = "Giancarlo",
                    LastName = "Stanton",
                    ImagePath = "",
                    Team = "NYY",
                    Position = "OF",
                    BattingAverage = ".266",
                    HomeRuns = "38",
                    Runs = "102",
                    RunsBattedIn = "100",
                    StolenBases = "5",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("e961b169-ab87-4e46-ac75-476f92369607"),
                    FirstName = "Ender",
                    LastName = "Inciarte",
                    ImagePath = "",
                    Team = "ATL",
                    Position = "OF",
                    BattingAverage = ".265",
                    HomeRuns = "10",
                    Runs = "83",
                    RunsBattedIn = "61",
                    StolenBases = "28",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("121982f2-526c-4d0d-afb0-b5827cc654af"),
                    FirstName = "Mitch",
                    LastName = "Haniger",
                    ImagePath = "",
                    Team = "SEA",
                    Position = "OF",
                    BattingAverage = ".285",
                    HomeRuns = "26",
                    Runs = "90",
                    RunsBattedIn = "93",
                    StolenBases = "8",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("211b7298-6b25-406c-96b1-f37b54368481"),
                    FirstName = "Marcell",
                    LastName = "Ozuna",
                    ImagePath = "",
                    Team = "STL",
                    Position = "OF",
                    BattingAverage = ".280",
                    HomeRuns = "23",
                    Runs = "69",
                    RunsBattedIn = "88",
                    StolenBases = "3",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("1b8f8b37-42d7-4fc9-b821-20045e6c84c2"),
                    FirstName = "Adam",
                    LastName = "Jones",
                    ImagePath = "",
                    Team = "BAL",
                    Position = "OF",
                    BattingAverage = ".281",
                    HomeRuns = "15",
                    Runs = "54",
                    RunsBattedIn = "63",
                    StolenBases = "7",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("69073dc0-f976-4c66-97c1-e198f395c1ac"),
                    FirstName = "Andrew",
                    LastName = "Benintendi",
                    ImagePath = "",
                    Team = "BOS",
                    Position = "OF",
                    BattingAverage = ".290",
                    HomeRuns = "16",
                    Runs = "103",
                    RunsBattedIn = "87",
                    StolenBases = "21",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("b72b6336-4e8a-4593-84d8-c739cfaadc00"),
                    FirstName = "Christian",
                    LastName = "Yelich",
                    ImagePath = "",
                    Team = "MIL",
                    Position = "OF",
                    BattingAverage = ".326",
                    HomeRuns = "36",
                    Runs = "118",
                    RunsBattedIn = "110",
                    StolenBases = "22",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("70aa8911-ed75-4dbf-9948-c0ed6ee545db"),
                    FirstName = "Michael",
                    LastName = "Brantley",
                    ImagePath = "",
                    Team = "CLE",
                    Position = "OF",
                    BattingAverage = ".309",
                    HomeRuns = "17",
                    Runs = "89",
                    RunsBattedIn = "76",
                    StolenBases = "12",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("8322b09e-9715-409b-93d3-e4eb3ea5adc1"),
                    FirstName = "J.D.",
                    LastName = "Martinez",
                    ImagePath = "",
                    Team = "BOS",
                    Position = "OF",
                    BattingAverage = ".330",
                    HomeRuns = "43",
                    Runs = "111",
                    RunsBattedIn = "130",
                    StolenBases = "6",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("efa4a840-8d5e-40f0-baf6-6c52b9bfe762"),
                    FirstName = "David",
                    LastName = "Peralta",
                    ImagePath = "",
                    Team = "ARI",
                    Position = "OF",
                    BattingAverage = ".293",
                    HomeRuns = "30",
                    Runs = "75",
                    RunsBattedIn = "87",
                    StolenBases = "4",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("3510d06e-f826-449f-8229-44f5998da8de"),
                    FirstName = "Mookie",
                    LastName = "Betts",
                    ImagePath = "",
                    Team = "BOS",
                    Position = "OF",
                    BattingAverage = ".346",
                    HomeRuns = "32",
                    Runs = "129",
                    RunsBattedIn = "80",
                    StolenBases = "30",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("d3afecc7-e1c9-4c8f-b8d5-088015319453"),
                    FirstName = "Max",
                    LastName = "Kepler",
                    ImagePath = "",
                    Team = "TEX",
                    Position = "OF",
                    BattingAverage = ".224",
                    HomeRuns = "20",
                    Runs = "80",
                    RunsBattedIn = "58",
                    StolenBases = "4",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("a9b09d66-80f7-461f-b1f0-46accd6f489f"),
                    FirstName = "Aaron",
                    LastName = "Hicks",
                    ImagePath = "",
                    Team = "NYY",
                    Position = "OF",
                    BattingAverage = ".248",
                    HomeRuns = "27",
                    Runs = "90",
                    RunsBattedIn = "79",
                    StolenBases = "11",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("c4f23289-71f7-41e8-b79f-d38f2c89a895"),
                    FirstName = "Andrew",
                    LastName = "McCutchen",
                    ImagePath = "",
                    Team = "PHI",
                    Position = "OF",
                    BattingAverage = ".255",
                    HomeRuns = "15",
                    Runs = "65",
                    RunsBattedIn = "55",
                    StolenBases = "13",
                    InningsPitched = "",
                    Wins = "",
                    Strikeouts = "",
                    EarnedRunAverage = "",
                    WHIP = ""
                },
                new Player()
                {
                    Id = new Guid("e6ffbf0d-ebee-424d-ad7e-8f858e403ed6"),
                    FirstName = "Max",
                    LastName = "Scherzer",
                    ImagePath = "",
                    Team = "WAS",
                    Position = "P",
                    BattingAverage = "",
                    HomeRuns = "",
                    Runs = "",
                    RunsBattedIn = "",
                    StolenBases = "",
                    InningsPitched = "220.2",
                    Wins = "18",
                    Strikeouts = "300",
                    EarnedRunAverage = "2.53",
                    WHIP = "0.91"
                },
                new Player()
                {
                    Id = new Guid("e1ef1d82-2c0d-4721-b4f0-aa7f958c3b67"),
                    FirstName = "Jacob",
                    LastName = "deGrom",
                    ImagePath = "",
                    Team = "NYM",
                    Position = "P",
                    BattingAverage = "",
                    HomeRuns = "",
                    Runs = "",
                    RunsBattedIn = "",
                    StolenBases = "",
                    InningsPitched = "217.0",
                    Wins = "10",
                    Strikeouts = "269",
                    EarnedRunAverage = "1.70",
                    WHIP = "0.91"
                },
                new Player()
                {
                    Id = new Guid("1762a454-6514-4dc3-82f8-85c2f4abe51c"),
                    FirstName = "Blake",
                    LastName = "Snell",
                    ImagePath = "",
                    Team = "TB",
                    Position = "P",
                    BattingAverage = "",
                    HomeRuns = "",
                    Runs = "",
                    RunsBattedIn = "",
                    StolenBases = "",
                    InningsPitched = "180.2",
                    Wins = "21",
                    Strikeouts = "221",
                    EarnedRunAverage = "1.89",
                    WHIP = "0.97"
                },
                new Player()
                {
                    Id = new Guid("a713c338-094a-4cc6-8a3f-cbefcc05fea8"),
                    FirstName = "Justin",
                    LastName = "Verlander",
                    ImagePath = "",
                    Team = "HOU",
                    Position = "P",
                    BattingAverage = "",
                    HomeRuns = "",
                    Runs = "",
                    RunsBattedIn = "",
                    StolenBases = "",
                    InningsPitched = "214.0",
                    Wins = "16",
                    Strikeouts = "290",
                    EarnedRunAverage = "2.52",
                    WHIP = "0.90"
                },
                new Player()
                {
                    Id = new Guid("283b66a5-f6e4-47e6-b41c-68d49406156f"),
                    FirstName = "Aaron",
                    LastName = "Nola",
                    ImagePath = "",
                    Team = "PHI",
                    Position = "P",
                    BattingAverage = "",
                    HomeRuns = "",
                    Runs = "",
                    RunsBattedIn = "",
                    StolenBases = "",
                    InningsPitched = "212.1",
                    Wins = "17",
                    Strikeouts = "224",
                    EarnedRunAverage = "2.37",
                    WHIP = "0.97"
                }
            };

            context.Players.AddRange(players);
            context.SaveChanges();
        }
    }
}